#!/usr/bin/env python3
"""Beat grid for the soundtrack: tempo (BPM) and first-beat offset of each track in assets/music/, plus the start of
its loudest section, written to src/core/audio/MusicTracks.inc so the game's visuals (BeatClock) pulse in time.

    python3 -m pip install numpy
    python3 scripts/audio/analyze_music.py        (macOS: decodes with afconvert)

The soundtrack is one track, played on the title screen and during runs (a surge speeds it up). Re-run after
replacing the file.
"""
import os
import struct
import subprocess
import sys
import tempfile
import wave

import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MUSIC = os.path.join(ROOT, "assets", "music")
OUT = os.path.join(ROOT, "src", "core", "audio", "MusicTracks.inc")
TRACKS = ["midnight_city_sprint.mp3"]  # the soundtrack (title + runs; a surge plays it faster)
SR = 22050


def decode(path):
    with tempfile.TemporaryDirectory() as tmp:
        wav = os.path.join(tmp, "t.wav")
        subprocess.run(["afconvert", "-f", "WAVE", "-d", f"LEI16@{SR}", "-c", "1", path, wav], check=True)
        with wave.open(wav) as w:
            return np.frombuffer(w.readframes(w.getnframes()), np.int16).astype(np.float32) / 32768.0


def onset_envelope(x, hop=128, n=2048):
    """Positive change in log energy over the whole spectrum (kicks, snares, hats), per frame."""
    frames = np.lib.stride_tricks.sliding_window_view(x, n)[::hop] * np.hanning(n)
    mag = np.abs(np.fft.rfft(frames, axis=1))
    f = np.fft.rfftfreq(n, 1 / SR)
    e = mag[:, (f > 35) & (f < 11000)].sum(1)
    on = np.maximum(0, np.diff(np.log1p(e)))
    return np.concatenate([[0], on]), SR / hop


def comb(on, fps, bpm, phases=24):
    """How strongly onsets line up on a beat grid at `bpm` (best phase), and that phase in frames."""
    per = 60 * fps / bpm
    idx = np.arange(0, len(on) - per, per)
    best, best_ph = -1.0, 0.0
    for ph in np.linspace(0, per, phases, endpoint=False):
        s = on[np.clip(np.round(idx + ph).astype(int), 0, len(on) - 1)].mean()
        if s > best: best, best_ph = s, ph
    return best, best_ph


def analyze(x):
    on, fps = onset_envelope(x)
    # tempo: each 30 s window votes for its best grid; syncopated sections favour 3:2 / 4:3 cousins of the real
    # tempo, so the most common winner is taken, then refined on the whole track and snapped to a whole BPM
    votes = []
    for w0 in range(0, int(len(on) / fps) - 30, 30):
        seg = on[int(w0 * fps):int((w0 + 30) * fps)]
        votes.append(max((comb(seg, fps, b)[0], b) for b in np.arange(90, 181, 0.25))[1])
    vals, counts = np.unique(np.round(votes), return_counts=True)
    guess = vals[np.argmax(counts)]
    bpm = max((comb(on, fps, b)[0], b) for b in np.arange(guess - 1, guess + 1, 0.01))[1]
    if abs(bpm - round(bpm)) < 0.15: bpm = float(round(bpm))
    _, ph = comb(on, fps, bpm, phases=96)
    offset = ph / fps                                # seconds to the first beat
    # loudest section: the 8-bar window with the highest RMS, snapped to a bar line
    bar = 4 * 60 / bpm
    rms = np.sqrt(np.convolve(x * x, np.ones(SR) / SR, "same"))[:: SR // 10]
    energy = np.convolve(rms, np.ones(int(8 * bar * 10)), "valid")
    start = np.argmax(energy) / 10
    start = offset + round((start - offset) / bar) * bar
    return bpm, offset, max(0.0, start), len(x) / SR


def main():
    lines = ["// Generated by scripts/audio/analyze_music.py; do not edit. Beat grid of the soundtrack (assets/music):",
             "// CS_MUSIC_TRACK(file symbol, bpm, first beat s, loudest section s, length s)"]
    for name in TRACKS:
        bpm, off, drop, length = analyze(decode(os.path.join(MUSIC, name)))
        sym = name.replace(".", "_")
        lines.append(f"CS_MUSIC_TRACK({sym}, {bpm:.2f}, {off:.3f}, {drop:.2f}, {length:.2f})")
        print(f"{name:26s} {bpm:6.2f} BPM, first beat {off:.3f} s, loudest section from {drop:.1f} s, {length:.1f} s")
    open(OUT, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
