// Generated by scripts/hud/make_hud_icons.py; do not edit. Frame indices into assets/hud/hud_icons.png.
#pragma once

namespace cs {

constexpr int kIconCols = 8, kIconRows = 9;

enum class Icon : int {
    Coin = 0,
    Flame = 8,
    ChestClosed = 12,
    ChestCrack = 13,
    ChestOpen = 14,
    Check = 15,
    Lock = 16,
    Rocket = 17,
    EggBolt = 18,
    Shop = 19,
    Locker = 20,
    Missions = 21,
    Trophy = 22,
    Share = 23,
    AdBadge = 24,
    NoAds = 25,
    Gift = 26,
    Star = 27,
    Bolt = 28,
    Bell = 29,
    Replay = 30,
    Plus = 31,
    Close = 32,
    Back = 33,
    Settings = 34,
    CoinGreen = 35,
    Chest3D = 36,
    MenuReplay = 37,
    MenuShop = 38,
    MenuLocker = 39,
    MenuMissions = 40,
    MenuFrame = 41,
    FrameTech = 42,
    FrameGlass = 43,
    FramePill = 44,
    Pile300 = 45,
    Pile1000 = 48,
    Pile1800 = 50,
    Pile4000 = 52,
    Pile9000 = 54,
    FrameFree = 56,
    FrameNeon = 58,
    BtnBlue = 60,
    BtnGold = 62,
    BtnDark = 64,
    RibbonBest = 66,
};

constexpr int kCoinFrames = 8;
constexpr int kFlameFrames = 4;

// sprites wider than one cell (coin piles, shop buttons and frames)
constexpr int iconSpan(Icon i) {
    switch (i) {
    case Icon::Pile300: return 2;
    case Icon::Pile1000: return 2;
    case Icon::Pile1800: return 2;
    case Icon::Pile4000: return 2;
    case Icon::Pile9000: return 2;
    case Icon::FrameFree: return 2;
    case Icon::FrameNeon: return 2;
    case Icon::BtnBlue: return 2;
    case Icon::BtnGold: return 2;
    case Icon::BtnDark: return 2;
    case Icon::RibbonBest: return 2;
    default: return 1;
    }
}

} // namespace cs
